environments:
  dev:
  staging:
  prod:

releases:
  - name: tinycloud-app-{{ .Environment.Name }}
    namespace: tinycloud-{{ .Environment.Name }}
    chart: oci://242902229138.dkr.ecr.eu-north-1.amazonaws.com/tinycloud-backend
    values:
      - {{ .Environment.Name }}/values-backend.yaml

  - name: tinycloud-frontend-{{ .Environment.Name }}
    namespace: tinycloud-{{ .Environment.Name }}
    chart: oci://242902229138.dkr.ecr.eu-north-1.amazonaws.com/tinycloud-frontend
    values:
      - {{ .Environment.Name }}/values-frontend.yaml
    