replicaCount: 1

image:
  repository: 242902229138.dkr.ecr.eu-north-1.amazonaws.com/tinycloud-docker-frontend
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-registry-secret

resources:
  limits:
    cpu: 50m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 16Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prod.hatstore-danil.info
  hosts:
    - host: prod.hatstore-danil.info
      paths:
        - path: /
          pathType: Prefix
  tls: []

backend:
  serviceName: tinycloud-backend-prod
  servicePort: 8080

env:
  BACKEND_HOST: tinycloud-backend-prod
  BACKEND_PORT: "8080"